TortoiseGMManager = TortoiseGMManager or {}
TortoiseGMManager.version = "0.5.3"

TortoiseGMManager.categories = {
    { id = "favourites", label = "Fav" },
    { id = "all", label = "All" },
    { id = "travel", label = "Travel" },
    { id = "player", label = "Player" },
    { id = "world", label = "World" },
    { id = "lookup", label = "Lookup" },
    { id = "admin", label = "Admin" },
{ id = "danger", label = "Danger" },
}

-- Command names and access levels are curated against Shyalya/tortoise-wow
-- playerbots-integration-gh, the default source built by TortoiseWoWServer.
-- Argument hints are intentionally concise; the UI can always ask the server
-- for `.help <command>` before execution.
TortoiseGMManager.commands = {
    { category = "quick", label = "GM mode ON", command = ".gm on", detail = "Enable GM mode for yourself.", access = "Moderator", direct = true },
    { category = "quick", label = "GM mode OFF", command = ".gm off", detail = "Disable GM mode for yourself.", access = "Moderator", direct = true },
    { category = "quick", label = "Visible", command = ".gm visible on", detail = "Make your GM character visible.", access = "Moderator", direct = true },
    { category = "quick", label = "Invisible", command = ".gm visible off", detail = "Hide your GM character at your access level.", access = "Moderator", direct = true },
    { category = "quick", label = "God ON", command = ".god on", detail = "Enable god mode on selected player, or self if none selected.", access = "Developer", direct = true },
    { category = "quick", label = "God OFF", command = ".god off", detail = "Disable god mode on selected player, or self if none selected.", access = "Developer", direct = true },
    { category = "quick", label = "GPS", command = ".gps", detail = "Show position and map information for the current target/context.", access = "Observer", direct = true },
    { category = "quick", label = "Revive", command = ".revive", detail = "Revive the selected player / supplied target according to server rules.", access = "Developer", direct = true },
    { category = "quick", label = "Replenish", command = ".replenish", detail = "Replenish the selected unit/player.", access = "Developer", direct = true },
    { category = "quick", label = "Repair items", command = ".repairitems", detail = "Repair all items for the selected player.", access = "Developer", direct = true },
    { category = "quick", label = "Respawn", command = ".respawn", detail = "Respawn the selected creature or nearby context.", access = "Developer", direct = true },
    { category = "quick", label = "Bank", command = ".bank", detail = "Open your bank UI.", access = "Developer", direct = true },
    { category = "quick", label = "Mailbox", command = ".mailbox", detail = "Open a mailbox UI.", access = "Developer", direct = true },
    { category = "quick", label = "Combat stop", command = ".combatstop", detail = "Stop combat for the selected player/unit.", access = "Moderator", direct = true },
    { category = "quick", label = "Recall", command = ".recall", detail = "Recall using the server's stored position semantics.", access = "Developer", direct = true },
    { category = "quick", label = "Save character", command = ".save", detail = "Save your character immediately.", access = "Developer", direct = true },
    { category = "quick", label = "Dismount", command = ".dismount", detail = "Dismount yourself when the server allows it.", access = "Developer", direct = true },
    { category = "quick", label = "Whispers ON", command = ".whispers on", detail = "Accept whispers while using the GM character.", access = "Moderator", direct = true },
    { category = "quick", label = "Whispers OFF", command = ".whispers off", detail = "Stop accepting whispers and clear allowed whisperers.", access = "Moderator", direct = true },

    { category = "travel", label = "Teleport", command = ".tele", hint = "saved location ID/name/partial name", detail = "Teleport to a saved game_tele destination. The server accepts an ID, exact name, or the first destination containing a partial name.", access = "Observer" },
{ category = "travel", label = "Tele: Stormwind", command = ".tele Stormwind", detail = "Teleport to Stormwind.", access = "Observer", direct = true },
{ category = "travel", label = "Tele: Ironforge", command = ".tele Ironforge", detail = "Teleport to Ironforge.", access = "Observer", direct = true },
{ category = "travel", label = "Tele: Darnassus", command = ".tele Darnassus", detail = "Teleport to Darnassus.", access = "Observer", direct = true },
{ category = "travel", label = "Tele: Orgrimmar", command = ".tele Orgrimmar", detail = "Teleport to Orgrimmar.", access = "Observer", direct = true },
{ category = "travel", label = "Tele: Thunder Bluff", command = ".tele Thunder Bluff", detail = "Teleport to Thunder Bluff.", access = "Observer", direct = true },
{ category = "travel", label = "Tele: Undercity", command = ".tele Undercity", detail = "Teleport to Undercity.", access = "Observer", direct = true },
{ category = "travel", label = "Tele: Booty Bay", command = ".tele Booty Bay", detail = "Teleport to Booty Bay.", access = "Observer", direct = true },
{ category = "travel", label = "Tele: Gadgetzan", command = ".tele Gadgetzan", detail = "Teleport to Gadgetzan.", access = "Observer", direct = true },
{ category = "travel", label = "Tele: Ratchet", command = ".tele Ratchet", detail = "Teleport to Ratchet.", access = "Observer", direct = true },
{ category = "travel", label = "Tele: Everlook", command = ".tele Everlook", detail = "Teleport to Everlook.", access = "Observer", direct = true },
{ category = "travel", label = "Tele: Moonglade", command = ".tele Moonglade", detail = "Teleport to Moonglade.", access = "Observer", direct = true },
{ category = "travel", label = "Tele: GM Island", command = ".tele GM Island", detail = "Teleport to GM Island.", access = "Observer", direct = true },
    { category = "travel", label = "Appear at player", command = ".goname", hint = "player name", detail = "Teleport yourself to a player.", access = "Observer" },
    { category = "travel", label = "Summon player", command = ".summon", hint = "player name", detail = "Summon a player to you.", access = "Moderator" },
    { category = "travel", label = "Go XYZ", command = ".go xyz", hint = "x y z [mapId]", detail = "Teleport to coordinates; mapId is optional and defaults to your current map.", access = "Observer" },
    { category = "travel", label = "Go creature", command = ".go creature", hint = "spawn GUID | partial creature name | id entry", detail = "Teleport to the nearest matching creature spawn; raw names are searched as substrings by the server.", access = "Observer" },
    { category = "travel", label = "Go object", command = ".go object", hint = "spawn GUID | partial object name | id entry", detail = "Teleport to the nearest matching gameobject spawn; raw names are searched as substrings by the server.", access = "Observer" },
    { category = "travel", label = "Go target", command = ".go target", detail = "Teleport directly to the currently selected unit on your map.", access = "Observer", direct = true },
    { category = "travel", label = "Forward", command = ".go forward", hint = "distance", detail = "Move forward by a distance.", access = "Observer" },
    { category = "travel", label = "Up", command = ".go up", hint = "distance", detail = "Move vertically by a distance.", access = "Observer" },
    { category = "travel", label = "Come to me", command = ".cometome", detail = "Move the selected creature/unit to your position.", access = "Developer", direct = true },
    { category = "travel", label = "Speed", command = ".modify speed", hint = "0..100", detail = "Set all movement speed multipliers on the selected unit.", access = "Developer" },
    { category = "travel", label = "Hover ON", command = ".hover 1", detail = "Enable hover for yourself.", access = "Administrator", direct = true },
    { category = "travel", label = "Hover OFF", command = ".hover 0", detail = "Disable hover for yourself.", access = "Administrator", direct = true },
    { category = "travel", label = "Waterwalk ON", command = ".waterwalk on", detail = "Enable water walking on the selected player.", access = "Developer", direct = true },
    { category = "travel", label = "Waterwalk OFF", command = ".waterwalk off", detail = "Disable water walking on the selected player.", access = "Developer", direct = true },
    { category = "travel", label = "All taxi nodes", command = ".taxicheat on", detail = "Enable all taxi paths for selected player or self.", access = "Developer", direct = true },
    { category = "travel", label = "Normal taxi nodes", command = ".taxicheat off", detail = "Disable taxi cheat for selected player or self.", access = "Developer", direct = true },
    { category = "travel", label = "Save teleport", command = ".tele add", hint = "location name", detail = "Persist your current position as a named game_tele destination.", access = "Developer", danger = true },
    { category = "travel", label = "Delete teleport", command = ".tele del", hint = "location name", detail = "Delete a saved game_tele destination by name.", access = "Developer", danger = true },
    { category = "travel", label = "Teleport player", command = ".tele name", hint = "[player] location", detail = "Teleport the selected/specified player, including an offline player, to a saved destination.", access = "Developer" },

    { category = "player", label = "Level up/down", command = ".levelup", hint = "[player] [delta]", detail = "Change level by a delta; defaults to +1 and can use the selected creature/player.", access = "Developer" },
    { category = "player", label = "Set HP", command = ".modify hp", hint = "current [max]", detail = "Modify HP values on the selected target.", access = "Developer" },
    { category = "player", label = "Set mana", command = ".modify mana", hint = "current [max]", detail = "Modify mana values on the selected target.", access = "Developer" },
    { category = "player", label = "Money", command = ".modify money", hint = "copper delta", detail = "Modify money for the selected player.", access = "Developer" },
    { category = "player", label = "Scale", command = ".modify scale", hint = "scale [on|off]", detail = "Change scale of the selected unit; the optional on/off flag controls persistence where supported by the handler.", access = "Developer" },
    { category = "player", label = "Add item", command = ".additem", hint = "itemId/itemLink [count]", detail = "Add item(s) to selected player. If you only know the item name, type it first and use FIND to search the server database.", access = "Developer", lookupCommand = ".lookup item", lookupHint = "an item name" },
    { category = "player", label = "Delete item", command = ".deleteitem", hint = "itemId/itemLink [count] [player]", detail = "Delete item(s) from the selected or specified player. Use FIND first when you only know the item name.", access = "Developer", danger = true, lookupCommand = ".lookup item", lookupHint = "an item name" },
    { category = "player", label = "Add item set", command = ".additemset", hint = "itemSetId/itemSetLink", detail = "Add every item belonging to an item set to selected player or self. Use FIND to resolve a set name.", access = "Developer", lookupCommand = ".lookup itemset", lookupHint = "an item-set name" },
    { category = "player", label = "Max skills", command = ".maxskill", detail = "Max skills for the selected player.", access = "Developer", direct = true },
    { category = "player", label = "Set skill", command = ".setskill", hint = "skillId value [max]", detail = "Set a skill on the selected player. Use FIND to resolve a skill name to its ID.", access = "Developer", lookupCommand = ".lookup skill", lookupHint = "a skill name" },
    { category = "player", label = "Clear cooldown", command = ".cooldown", hint = "[spellId/spellLink]", detail = "Clear cooldowns according to server syntax. Use FIND to resolve a spell name.", access = "Developer", lookupCommand = ".lookup spell", lookupHint = "a spell name" },
    { category = "player", label = "Add aura", command = ".aura", hint = "spellId/spellLink [durationSeconds]", detail = "Apply an aura to the selected unit, optionally for a duration. Use FIND to resolve a spell name.", access = "Developer", lookupCommand = ".lookup spell", lookupHint = "a spell name" },
    { category = "player", label = "Remove aura", command = ".unaura", hint = "spellId/spellLink / all", detail = "Remove aura(s) from the selected unit. Use FIND to resolve a spell name.", access = "Developer", lookupCommand = ".lookup spell", lookupHint = "a spell name" },
    { category = "player", label = "Cast", command = ".cast", hint = "spellId/spellLink [triggered]", detail = "Cast a spell; administrators can cast on the selected unit, while lower security is forced to self. Use FIND to resolve a spell name.", access = "Developer", lookupCommand = ".lookup spell", lookupHint = "a spell name" },
    { category = "player", label = "Unlearn", command = ".unlearn", hint = "spellId/spellLink", detail = "Unlearn a spell from selected player. Use FIND to resolve a spell name.", access = "Developer", lookupCommand = ".lookup spell", lookupHint = "a spell name" },
    { category = "player", label = "Player info", command = ".pinfo", hint = "[player]", detail = "Show player/account information allowed by your access level.", access = "Moderator" },
    { category = "player", label = "GUID", command = ".guid", detail = "Show GUID of the selected object/unit.", access = "Moderator", direct = true },
    { category = "player", label = "Explore all", command = ".explorecheat 1", detail = "Mark exploration flags using the selected-player command path.", access = "Developer", direct = true },
    { category = "player", label = "Clear exploration", command = ".explorecheat 0", detail = "Clear exploration flags using the selected-player command path.", access = "Developer", direct = true },
    { category = "player", label = "Morph", command = ".modify morph", hint = "displayId", detail = "Set display ID on selected unit, or self when no unit is selected.", access = "Developer" },
{ category = "player", label = "Morph: Human", command = ".modify morph 49", detail = "Apply the common Human display ID.", access = "Developer", direct = true },
{ category = "player", label = "Morph: Orc", command = ".modify morph 51", detail = "Apply the common Orc display ID.", access = "Developer", direct = true },
{ category = "player", label = "Morph: Dwarf", command = ".modify morph 53", detail = "Apply the common Dwarf display ID.", access = "Developer", direct = true },
{ category = "player", label = "Morph: Night Elf", command = ".modify morph 55", detail = "Apply the common Night Elf display ID.", access = "Developer", direct = true },
{ category = "player", label = "Morph: Undead", command = ".modify morph 57", detail = "Apply the common Undead display ID.", access = "Developer", direct = true },
{ category = "player", label = "Morph: Tauren", command = ".modify morph 59", detail = "Apply the common Tauren display ID.", access = "Developer", direct = true },
{ category = "player", label = "Morph: Troll", command = ".modify morph 1478", detail = "Apply the common Troll display ID.", access = "Developer", direct = true },
{ category = "player", label = "Morph: Gnome", command = ".modify morph 1563", detail = "Apply the common Gnome display ID.", access = "Developer", direct = true },
    { category = "player", label = "Demorph", command = ".demorph", detail = "Restore the selected unit's normal display.", access = "Moderator", direct = true },
    { category = "player", label = "Learn spell", command = ".learn", hint = "spellId/spellLink", detail = "Teach a spell to the selected player. Use FIND to resolve a spell name.", access = "Developer", lookupCommand = ".lookup spell", lookupHint = "a spell name" },
    { category = "player", label = "Learn class spells", command = ".learn all_myspells", detail = "Teach all class spells supported by the server.", access = "Developer", danger = true, direct = true },
    { category = "player", label = "Learn recipes", command = ".learn all_recipes", detail = "Teach all recipes supported by the server.", access = "Developer", danger = true, direct = true },
    { category = "player", label = "Learn trainer spells", command = ".learn all_trainer", detail = "Teach all trainer spells supported by the server.", access = "Developer", danger = true, direct = true },
    { category = "player", label = "Learn item spells", command = ".learn all_items", detail = "Teach all item-learned spells supported by the server.", access = "Developer", danger = true, direct = true },

    { category = "world", label = "NPC info", command = ".npc info", detail = "Inspect the selected creature.", access = "Developer", direct = true },
    { category = "world", label = "Nearby NPCs", command = ".npc near", hint = "[distance]", detail = "List nearby creatures.", access = "Developer" },
    { category = "world", label = "Add NPC", command = ".npc add", hint = "creature entry", detail = "Create a persistent creature spawn at your position. Use FIND to search creature templates by name first.", access = "Developer", danger = true, lookupCommand = ".lookup creature", lookupHint = "a creature name" },
    { category = "world", label = "Summon NPC", command = ".npc summon", hint = "creature entry", detail = "Summon a temporary creature at your position. Use FIND to search creature templates by name first.", access = "Developer", lookupCommand = ".lookup creature", lookupHint = "a creature name" },
    { category = "world", label = "Move NPC", command = ".npc move", hint = "[spawn GUID]", detail = "Move the selected/spawned creature according to server syntax.", access = "Developer", danger = true },
{ category = "world", label = "NPC movement: idle", command = ".npc spawn set movetype idle NODEL", detail = "Make the selected spawn stay idle without deleting its waypoints.", access = "Developer", danger = true, direct = true },
{ category = "world", label = "NPC movement: random", command = ".npc spawn set movetype random NODEL", detail = "Give the selected spawn random movement without deleting its waypoints.", access = "Developer", danger = true, direct = true },
{ category = "world", label = "NPC movement: waypoint", command = ".npc spawn set movetype waypoint NODEL", detail = "Give the selected spawn waypoint movement without deleting its waypoints.", access = "Developer", danger = true, direct = true },
    { category = "world", label = "NPC say", command = ".npc say", hint = "text", detail = "Make the selected creature say text.", access = "Developer" },
    { category = "world", label = "NPC yell", command = ".npc yell", hint = "text", detail = "Make the selected creature yell text.", access = "Developer" },
    { category = "world", label = "NPC emote", command = ".npc playemote", hint = "emoteId", detail = "Play an emote on the selected creature.", access = "Developer" },
    { category = "world", label = "Delete NPC", command = ".npc delete", hint = "[spawn GUID]", detail = "Delete the selected creature spawn.", access = "Developer", danger = true },
    { category = "world", label = "Quest add", command = ".quest add", hint = "questId [player]", detail = "Add a quest to selected/specified player. Use FIND to resolve a quest title to its ID.", access = "Developer", lookupCommand = ".lookup quest", lookupHint = "a quest title" },
    { category = "world", label = "Quest complete", command = ".quest complete", hint = "questId [player]", detail = "Complete a quest for selected/specified player. Use FIND to resolve a quest title to its ID.", access = "Developer", lookupCommand = ".lookup quest", lookupHint = "a quest title" },
    { category = "world", label = "Quest status", command = ".quest status", hint = "questId [player]", detail = "Inspect quest status for the selected or specified player. Use FIND to resolve a quest title to its ID.", access = "Moderator", lookupCommand = ".lookup quest", lookupHint = "a quest title" },
    { category = "world", label = "Quest remove", command = ".quest remove", hint = "questId [player]", detail = "Remove/reset a quest for selected/specified player. Use FIND to resolve a quest title to its ID.", access = "Developer", danger = true, lookupCommand = ".lookup quest", lookupHint = "a quest title" },
    { category = "world", label = "Event list", command = ".event list", detail = "List game events.", access = "Administrator", direct = true },
    { category = "world", label = "Event start", command = ".event start", hint = "eventId", detail = "Start a game event. Use FIND to search events by name.", access = "Administrator", danger = true, lookupCommand = ".lookup event", lookupHint = "an event name" },
    { category = "world", label = "Event stop", command = ".event stop", hint = "eventId", detail = "Stop a game event. Use FIND to search events by name.", access = "Administrator", danger = true, lookupCommand = ".lookup event", lookupHint = "an event name" },
    { category = "world", label = "Nearby triggers", command = ".trigger near", hint = "[distance]", detail = "List nearby area triggers.", access = "Observer" },
    { category = "world", label = "List creatures", command = ".list creature", hint = "entry [count]", detail = "List creature spawns matching an entry. Use FIND to resolve a creature name to its template ID.", access = "Developer", lookupCommand = ".lookup creature", lookupHint = "a creature name" },
    { category = "world", label = "List objects", command = ".list object", hint = "entry [count]", detail = "List gameobject spawns matching an entry. Use FIND to resolve an object name to its template ID.", access = "Developer", lookupCommand = ".lookup object", lookupHint = "a gameobject name" },
    { category = "world", label = "Add gameobject", command = ".gobject add", hint = "objectEntry [respawnSeconds]", detail = "Create and persist a gameobject at your position. Use FIND to resolve an object name.", access = "Developer", danger = true, lookupCommand = ".lookup object", lookupHint = "a gameobject name" },
    { category = "world", label = "Target gameobject", command = ".gobject target", hint = "[entry/name]", detail = "Find the nearest matching gameobject on your current map.", access = "Developer" },
    { category = "world", label = "Delete gameobject", command = ".gobject delete", hint = "[spawn GUID]", detail = "Delete the selected or specified persistent gameobject.", access = "Developer", danger = true },

    { category = "lookup", label = "Item", command = ".lookup item", hint = "partial item name", detail = "Search item templates by name and return matching IDs/links.", access = "Moderator" },
    { category = "lookup", label = "Quest", command = ".lookup quest", hint = "partial quest title", detail = "Search quests by title and return matching IDs.", access = "Moderator" },
    { category = "lookup", label = "Spell", command = ".lookup spell", hint = "partial spell name", detail = "Search spells by name and return matching IDs/links.", access = "Moderator" },
    { category = "lookup", label = "Creature", command = ".lookup creature", hint = "partial creature name", detail = "Search creature templates by name and return entry IDs.", access = "Moderator" },
    { category = "lookup", label = "Object", command = ".lookup object", hint = "partial object name", detail = "Search gameobject templates by name and return entry IDs.", access = "Moderator" },
    { category = "lookup", label = "Faction", command = ".lookup faction", hint = "partial faction name", detail = "Search factions by name and return IDs.", access = "Moderator" },
    { category = "lookup", label = "Skill", command = ".lookup skill", hint = "partial skill name", detail = "Search skills by name and return IDs.", access = "Moderator" },
    { category = "lookup", label = "Item set", command = ".lookup itemset", hint = "partial item-set name", detail = "Search item sets by name and return IDs.", access = "Moderator" },
    { category = "lookup", label = "Event", command = ".lookup event", hint = "partial event name", detail = "Search game events by name and return event IDs.", access = "Moderator" },
    { category = "lookup", label = "Guild", command = ".lookup guild", hint = "\"exact guild name\"", detail = "Show details for an exact guild name; the server expects the name quoted.", access = "Moderator" },
    { category = "lookup", label = "Player name", command = ".lookup player name", hint = "partial character name [limit]", detail = "Search character records directly by partial character name.", access = "Moderator" },
    { category = "lookup", label = "Player by account", command = ".lookup player account", hint = "account [limit]", detail = "Find characters associated with matching account names.", access = "Moderator" },
    { category = "lookup", label = "Player by email", command = ".lookup player email", hint = "email [limit]", detail = "Find characters through matching account email.", access = "Moderator" },
    { category = "lookup", label = "Player by IP", command = ".lookup player ip", hint = "IP [limit]", detail = "Find characters through matching account last-IP data.", access = "Moderator" },
    { category = "lookup", label = "Related by character", command = ".lookup player character", hint = "character name [limit]", detail = "Resolve a character and search accounts/characters related through that account's last IP.", access = "Moderator" },
    { category = "lookup", label = "Hardware fingerprint", command = ".lookup hwprint", hint = "numeric extended HWPrint", detail = "List accounts matching an extended hardware fingerprint.", access = "Developer" },

    { category = "admin", label = "Online GMs", command = ".gm ingame", detail = "List GMs currently in game.", access = "Moderator", direct = true },
    { category = "admin", label = "Full GM list", command = ".gm list", detail = "List GM accounts/characters according to server access.", access = "Developer", direct = true },
    { category = "admin", label = "Commands", command = ".commands", detail = "Ask the server for commands available to your account.", access = "Player", direct = true },
    { category = "admin", label = "Server info", command = ".server info", detail = "Show server information.", access = "Player", direct = true },
    { category = "admin", label = "Save all", command = ".saveall", detail = "Save all online players.", access = "Administrator", direct = true },
    { category = "admin", label = "Reload config", command = ".reload config", detail = "Reload world configuration and anticheat settings.", access = "Administrator", danger = true, direct = true },
    { category = "admin", label = "Reload housing", command = ".reload housing", detail = "Reload guild housing data.", access = "Developer", danger = true, direct = true },
    { category = "admin", label = "Broadcast", command = ".broadcast", hint = "message", detail = "Broadcast a system message globally.", access = "Administrator" },
    { category = "admin", label = "Notify", command = ".notify", hint = "message", detail = "Send a global on-screen notification.", access = "Administrator" },
    { category = "admin", label = "Kick", command = ".kick", hint = "player [reason]", detail = "Kick a player.", access = "Moderator", danger = true },
    { category = "admin", label = "Mute", command = ".mute", hint = "player duration reason", detail = "Mute a player/account according to server syntax.", access = "Moderator", danger = true },
    { category = "admin", label = "Unmute", command = ".unmute", hint = "player/account", detail = "Remove a mute.", access = "Moderator", danger = true },
    { category = "admin", label = "Ban character", command = ".ban character", hint = "name duration reason", detail = "Ban a character target.", access = "Moderator", danger = true },
    { category = "admin", label = "Ban account", command = ".ban account", hint = "account duration reason", detail = "Ban an account.", access = "Moderator", danger = true },
    { category = "admin", label = "Ban IP", command = ".ban ip", hint = "ip duration reason", detail = "Ban an IP address.", access = "Moderator", danger = true },
    { category = "admin", label = "Unban character", command = ".unban character", hint = "name", detail = "Remove a character ban.", access = "Developer", danger = true },
    { category = "admin", label = "Unban account", command = ".unban account", hint = "account", detail = "Remove an account ban.", access = "Developer", danger = true },
    { category = "admin", label = "Unban IP", command = ".unban ip", hint = "ip", detail = "Remove an IP ban.", access = "Developer", danger = true },

    { category = "danger", label = "Server restart", command = ".server restart", hint = "delaySeconds [exitCode]", detail = "Schedule a server restart. Requires double-run confirmation in this addon.", access = "Administrator", danger = true },
    { category = "danger", label = "Cancel restart", command = ".server restart cancel", detail = "Cancel a pending restart timer.", access = "Administrator", direct = true },
{ category = "danger", label = "Cancel shutdown", command = ".server shutdown cancel", detail = "Cancel a pending shutdown timer.", access = "Administrator", direct = true },
    { category = "danger", label = "Server shutdown", command = ".server shutdown", hint = "delaySeconds [exitCode]", detail = "Schedule a server shutdown. Requires double-run confirmation in this addon.", access = "Administrator", danger = true },
    { category = "danger", label = "Reset all raids", command = ".server resetallraids", detail = "Reset all raid instances. Requires double-run confirmation.", access = "Administrator", danger = true, direct = true },
    { category = "danger", label = "Kill selected", command = ".die", detail = "Kill the selected unit. Requires double-run confirmation.", access = "Developer", danger = true, direct = true },
}

TortoiseGMManager.safeCommands = {
    [".server restart cancel"] = true,
    [".server shutdown cancel"] = true,
    [".server idlerestart cancel"] = true,
    [".server idleshutdown cancel"] = true,
}

TortoiseGMManager.dangerPrefixes = {
    ".server restart",
    ".server shutdown",
    ".server idlerestart",
    ".server idleshutdown",
    ".server resetallraids",
    ".ban",
    ".unban",
    ".kick",
    ".mute",
    ".unmute",
    ".npc delete",
    ".npc add",
".npc move",
".npc spawn set movetype",
".quest remove",
    ".event start",
    ".event stop",
    ".deleteitem",
    ".reload",
    ".gobject add",
    ".gobject delete",
    ".tele add",
    ".tele del",
    ".learn all_myspells",
    ".learn all_recipes",
    ".learn all_trainer",
    ".learn all_items",
    ".die",
}
